apiVersion: v1
kind: ConfigMap
metadata:
  name: kcl-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kcl
    spec:
      version: v1.0
      generate:
        command: ["sh", "-c"]
        args:
          - |
            export KCL_CACHE_PATH=$(mktemp -d /tmp/kcl_cache.XXXXXXXXXX)
            export KCL_PKG_PATH=$(mktemp -d /tmp/kcl_pkg.XXXXXXXXXX)
            temp_dir=$(mktemp -d /tmp/debug.XXXXXXXXXX)
            tempfile="$temp_dir/output.txt"
            modupdate="$temp_dir/modupdate.txt"
            err_file="$temp_dir/err_file.txt"
            kcl mod update >$modupdate 2>&1
            kcl run >$tempfile 2>$err_file
            error=$?
            if [ $error -eq 0 ]; then
              cat $tempfile
            fi
            exit $error
