apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  controller.repo.server.timeout.seconds: "600"
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  server.repo.server.timeout.seconds: "600"
  statusbadge.enabled: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 10m
  url: https://argocd.example.com

