name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  redeploy_cluster:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Redeploy the k3s cluster
      run: make mindwm_lifecycle
